#!/usr/bin/perl -w

use strict;

print <<EOD;
/* This is an AUTOGENERATED file from IANA registered headers descpriptions.
 */

#ifndef PUSHKIN_HTTP_COMMON_HEADER_NAMES_HPP_
#define PUSHKIN_HTTP_COMMON_HEADER_NAMES_HPP_

namespace psst {
namespace http {

enum known_header_name {
EOD

while (<>) {
	s/\r\n//g;
	my ($header, $template, $protocol, $status, $reference) = split(',', $_, 5);
	$reference =~ s/"//g;
	$reference =~ s/\n//;
	my $enum_val = $header;
	$enum_val =~ s/-//g;
	$status ||= "provisional";

	print "\t$enum_val, /**< $header: $reference ($status) $template */\n";
}

print <<EOD;

};

}  // namespace http
}  // namespace psst

#endif /* PUSHKIN_HTTP_COMMON_HEADER_NAMES_HPP_ */
EOD

